workflows:
  ios-unsigned-build:
    name: Build Unsigned iOS IPA (sideload via Sideloadly)
    max_build_duration: 30
    instance_type: mac_mini_m1
    working_directory: fyp_flutter
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: cd ios && pod install
      - name: Build unsigned ipa
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r Runner.ipa Payload
          echo "PWD is: $(pwd)"
          echo "CM_EXPORT_DIR is: $CM_EXPORT_DIR"
          ls -la Runner.ipa
          cp Runner.ipa "$CM_EXPORT_DIR/Runner.ipa"
          ls -la "$CM_EXPORT_DIR"
    artifacts:
      - "**/*.ipa"
