"""baseline: existing schema as of 2026-07-30

Revision ID: 71c97fdeebc7
Revises: 
Create Date: 2026-07-30 19:25:18.929290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c97fdeebc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Intentionally empty — applied with `alembic stamp head`, not `upgrade`.

    The 18 tables already existed (created by the old create_all + hand-written
    ALTER TABLE block in main.py), so this revision only declares "the schema as
    it stands today is version 1". It is deliberately NOT autogenerated: the live
    DB and models.py disagree at this point, so autogenerate would have emitted
    DROP COLUMN for the four shadow columns before the next revision backfills
    them. Every change from here on is an explicit incremental revision.
    """
    pass


def downgrade() -> None:
    pass
